# -*- coding: utf-8 -*-
"""Conversione Turni.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2a3N8Qtm2_lEqyO-CYtFA8d9CZmX4Cb
"""

import pandas as pd
import streamlit as st

df = pd.read_excel(excel_file_path)


found_index = -1
for index, row in df.iterrows():
    if str(row.iloc[0]).lower().find(surname) != -1:
        found_index = index
        break # Stop the loop once the surname is found

if found_index != -1:
    morning = df.iloc[found_index - 1]
    afternoon = df.iloc[found_index]
    night = df.iloc[found_index + 1]

# Define the columns
columns = [
    "Subject",
    "Start Date",
    "Start Time",
    "End Date",
    "End Time",
    "All Day Event"
]

df_morning = pd.DataFrame(columns=columns)

if morning is not None: # Check if morning row was found
    for date, shift in morning.iloc[1:].items():
        if pd.notna(shift): # Only add if the shift is not NaN
            new_row = {
                "Subject": shift,
                "Start Date": date.strftime('%d-%m-%Y'),
                "Start Time": "8:00 AM",
                "End Date": date.strftime('%d-%m-%Y'),
                "End Time": "2:00 PM",
                "All Day Event": "False"
            }
            df_morning = pd.concat([df_morning, pd.DataFrame([new_row])], ignore_index=True)

df_afternoon = pd.DataFrame(columns=columns)

if afternoon is not None: # Check if afternoon row was found
    for date, shift in afternoon.iloc[1:].items():
        if pd.notna(shift): # Only add if the shift is not NaN
            new_row = {
                "Subject": shift,
                "Start Date": date.strftime('%d-%m-%Y'),
                "Start Time": "2:00 PM",
                "End Date": date.strftime('%d-%m-%Y'),
                "End Time": "8:00 PM",
                "All Day Event": "False"
            }
            df_afternoon = pd.concat([df_afternoon, pd.DataFrame([new_row])], ignore_index=True)

df_night = pd.DataFrame(columns=columns)

if night is not None: # Check if night row was found
    for date, shift in night.iloc[1:].items():
        if pd.notna(shift): # Only add if the shift is not NaN
            new_row = {
                "Subject": shift,
                "Start Date": date.strftime('%d-%m-%Y'),
                "Start Time": "8:00 PM",
                "End Date": (date + pd.Timedelta(days=1)).strftime('%d-%m-%Y'),
                "End Time": "8:00 AM",
                "All Day Event": "False"
            }
            df_night = pd.concat([df_night, pd.DataFrame([new_row])], ignore_index=True)

df_final = pd.concat([df_morning, df_afternoon, df_night], ignore_index=True)

